// prettier-ignore
const theme = {
	primaryColor:	 		"#0F7891",
	primaryHigher: 		"#30B4D2",
	primaryHigh: 			"#2091AC",
	primaryLow: 			"#145C6D",
	primaryLower: 		"#0E4855",
	secondaryColor: 	"#EA7D12",
	secondaryHigh: 		"#FF9935",
	secondaryHigher:	"#FF9329",
	secondaryLow: 		"#B0661C",
	secondaryLower: 	"#894E14",

	darkBackground: 				"#0f1322",
	darkBackgroundGradient: "#0b070f",
}

export default theme;

/*

#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=70z0G0ktztppnMjqU-HqTm5rqhf


*** Primary color:

   shade 0 = #EA7D12 = rgb(234,125, 18) = rgba(234,125, 18,1) = rgb0(0.918,0.49,0.071)
   shade 1 = #FF9935 = rgb(255,153, 53) = rgba(255,153, 53,1) = rgb0(1,0.6,0.208)
   shade 2 = #FF9329 = rgb(255,147, 41) = rgba(255,147, 41,1) = rgb0(1,0.576,0.161)
   shade 3 = #B0661C = rgb(176,102, 28) = rgba(176,102, 28,1) = rgb0(0.69,0.4,0.11)
   shade 4 = #894E14 = rgb(137, 78, 20) = rgba(137, 78, 20,1) = rgb0(0.537,0.306,0.078)

*** Secondary color (1):

   shade 0 = #EAB812 = rgb(234,184, 18) = rgba(234,184, 18,1) = rgb0(0.918,0.722,0.071)
   shade 1 = #FFD035 = rgb(255,208, 53) = rgba(255,208, 53,1) = rgb0(1,0.816,0.208)
   shade 2 = #FFCD29 = rgb(255,205, 41) = rgba(255,205, 41,1) = rgb0(1,0.804,0.161)
   shade 3 = #B08D1C = rgb(176,141, 28) = rgba(176,141, 28,1) = rgb0(0.69,0.553,0.11)
   shade 4 = #896E14 = rgb(137,110, 20) = rgba(137,110, 20,1) = rgb0(0.537,0.431,0.078)

*** Secondary color (2):

   shade 0 = #2922A3 = rgb( 41, 34,163) = rgba( 41, 34,163,1) = rgb0(0.161,0.133,0.639)
   shade 1 = #4F46DC = rgb( 79, 70,220) = rgba( 79, 70,220,1) = rgb0(0.31,0.275,0.863)
   shade 2 = #3C35BD = rgb( 60, 53,189) = rgba( 60, 53,189,1) = rgb0(0.235,0.208,0.741)
   shade 3 = #27227B = rgb( 39, 34,123) = rgba( 39, 34,123,1) = rgb0(0.153,0.133,0.482)
   shade 4 = #1D1960 = rgb( 29, 25, 96) = rgba( 29, 25, 96,1) = rgb0(0.114,0.098,0.376)

*** Complement color:

   shade 0 = #0F7891 = rgb( 15,120,145) = rgba( 15,120,145,1) = rgb0(0.059,0.471,0.569)
   shade 1 = #30B4D2 = rgb( 48,180,210) = rgba( 48,180,210,1) = rgb0(0.188,0.706,0.824)
   shade 2 = #2091AC = rgb( 32,145,172) = rgba( 32,145,172,1) = rgb0(0.125,0.569,0.675)
   shade 3 = #145C6D = rgb( 20, 92,109) = rgba( 20, 92,109,1) = rgb0(0.078,0.361,0.427)
   shade 4 = #0E4855 = rgb( 14, 72, 85) = rgba( 14, 72, 85,1) = rgb0(0.055,0.282,0.333)


#####  Generated by Paletton.com (c) 2002-2014

*/
